mansiruhil/fail-u-forward

readme.md

The readme.md file is enhanced with appropriate emojis beside each section headers to make it look more appealing.
Added a Contact Section with the admin's GitHub and LinkedIn links.
For easy navigation, a Table of Contents has been added at the beginning with links to the respective section headers.
Sending this as a PR , hope you merge it ❤️

Enhanced readme.md with emojis, TOC and contact section

---

app/register/page.tsx

This Pull request addresses to the issue number #11 to ensure consistent and accessible color contrast across all form labels and inputs. Modified the relevant CSS styles affecting the form typography.
Changes Made:
- Updated font color in the register form styles.
- Verified responsiveness and readability across different devices.
please review and suggest if any further changes are required @mansiruhil !

Styled for Impact: Updated Font Color in Registration Form!

---

app/feed/page.tsx

Reapplying the PR because the previous one was not merged properly. #3 Issue

Reapplying merged changes to trigger proper deployment

---

app/feed/page.tsx

Reverts mansiruhil/fail-u-forward#27

Revert "Reapplying merged changes to trigger proper deployment"

---

app/page.tsx

This PR fixes #19 #20 
- Initially the landing page buttons had a lot of scaling on hover, I have fixed that by reducing the scaling.
- I have add some animation to the arrow button
- Fixed the intensity of the texts so it doesn't mix up with the background
[Screencast from 2025-07-24 12-20-38.webm](https://github.com/user-attachments/assets/c6cf33d6-2dd7-4733-bfee-2a27073642a2)

Improved the ui of button

---

app/register/page.tsx

This PR fixes #42 
Changes that were made:
- Fixed the text color of Email
- Added password visibility toggle button
- Added text that shows the strength of password
Approach for this problem:
I have used regex to validate password with multiple checks

Added password validation

---

components/feed/feed.tsx
components/layout/navbar.tsx

Reverts mansiruhil/fail-u-forward#37

Revert "Fixed logout from feed page"

---

Contributing.md
readme.md

This PR adds a detailed CONTRIBUTING.md file to help beginners understand the steps involved in contributing to the project. It includes:
Instructions for forking and cloning the repo
Guidelines for creating a new branch
Steps for setting up the project locally
Commands for committing and pushing changes
Instructions to open a pull request
Additionally, a link to the CONTRIBUTING.md has been added in the README.md under a new Contributing section.

Added CONTRIBUTING.md and linked it in README

---

app/about/page.tsx
package-lock.json
package.json

PR for issue #117 
This PR enhances the overall UI by addressing layout clarity and visual engagement:
Checklist:
- Layout spacing audited and updated
- Text styles aligned with visual hierarchy principles
- Background graphics tested for responsiveness and contrast
- Cross-browser and mobile responsiveness verified

changed the about page layout added dynamic background.

---

app/feed/page.tsx
app/globals.css
app/layout.tsx
app/profile/page.tsx
components/layout/navbar.tsx
components/post/create-post.tsx
components/sidebar/leftsidebar.tsx
components/sidebar/rightsidebar.jsx
components/theme-toggle.tsx
components/ui/button.tsx
components/ui/card.tsx
components/ui/dropdown-menu.tsx
components/ui/input.tsx
components/ui/textarea.tsx

This PR fixes #133 #132
I have added appropriate classname to fix the theme change on toggling darkmode
Here's a demo loom video
https://www.loom.com/share/4147e5dafa7249bbb1d3fab4cf365064?sid=90d63ee3-220f-457c-b2f6-d3b8c012f2e7

Fixing theme by adding classes

---

components/layout/navbar.tsx

This PR fixes #55 issue
I have improved the ui of navigation sidebar in mobile view
Here's comparison of before:
after:

Fixed the navbar in mobile view

---

components/sidebar/rightsidebar.jsx

What this PR does:
- Removes random counts
- Adds arrow navigation animation
- Adds tags with hover animation
updates for #130 
loom video: https://www.loom.com/share/ef49404de31e425781407bf30836f98a?sid=0570bb3b-4337-4c08-b707-63a1ddb1f5b0

Adding animation to right sidebar

---

components/sidebar/rightsidebar.jsx

Reverts mansiruhil/fail-u-forward#172

Revert "Adding animation to right sidebar"

---

components/sidebar/rightsidebar.jsx

Reverts mansiruhil/fail-u-forward#173

Revert "Revert "Adding animation to right sidebar""

---

app/about/page.tsx

Issue #165 
Made visible social media icons  in about page.
- Add toggle animation feature in the icons.
- keep visibility of icons
- add hover

update social media icon

---

app/accessibility.css
app/api/follow/route.ts
app/api/users/[userId]/route.ts
app/messages/page.tsx
app/post/[id]/page.tsx
app/profile/[userId]/page.tsx
app/profile/page.tsx
components/post/create-post.tsx
components/sidebar/leftsidebar.tsx
components/ui/follow-button.tsx

Image 1: Anonymous user viewing SHIPRA 99's profile (0 followers initially)
Image 2: Anonymous user followed SHIPRA 99 (count increased to 1 follower)
Image 3: Anonymous user's own profile showing "1 Following" (the action is reflected).

 implemented user follow/unfollow functionality

---

app/accessibility.css
app/api/upload/route.ts
app/profile/page.tsx

Changes: 
1. When a profile picture is uploaded, it is now updated properly.
2. Added a save button to save the changes
3. The type fields are now visible with black borders and with a darker border when a type field is selected

Built user friendly edit profile section  #166

---

app/api/chatbot/route.ts
app/api/check-username/route.ts
app/api/follow/route.ts
app/api/news/route.ts
app/api/post/[id]/comment/route.ts
app/api/post/[id]/dislike/route.ts
app/api/post/[id]/edit/route.ts
app/api/post/[id]/like/route.ts
app/api/post/[id]/reaction/route.ts
app/api/post/[id]/share/route.ts
app/api/post/route.ts
app/api/upload/route.ts
app/api/users/[userId]/route.ts
app/api/validate/route.ts
services/ai.ts
services/follow.ts
services/news.ts
services/posts.ts
services/username.ts
services/users.ts
services/validation.ts

This PR refactors the Next.js API route handlers to improve **maintainability, readability, and consistency**.
- Extracted **business logic** from API route handlers into a dedicated **service layer**.
- Added a **standardized response format** for all API responses:
```json
{
"success": boolean,
"data": any,
"error": string | null
}
Closes #191

refactor(api): move business logic to service layer

---

app/about/page.tsx
app/login/page.tsx
app/register/page.tsx
package-lock.json
package.json

Enhanced Sign Up and Login Pages Properly
Closes #207

Fixes SignUp and Login Pages

---

components/layout/navbar.tsx
package-lock.json

This pull request enhances the **Header component** and the **Sign In form** by improving the layout, design consistency, and user experience. The updates make the interface look more polished, professional, and user-friendly while maintaining responsiveness across different devices.
- Added a simple bag icon next to the site title to create a more formal and professional appearance.
- Improved alignment and spacing to ensure a balanced layout that feels modern and intuitive.
- Refined the background animation with better connections between points, contributing to a sleek and dynamic interface.
- Adjusted spacing and structure to create a cleaner and more approachable look.
- These changes are strictly related to the frontend appearance and usability; no backend or API logic was …

Fix: update header component layout

---

.github/ISSUE_TEMPLATE/bug_report.md
.github/ISSUE_TEMPLATE/feature_request.md
.github/PULL_REQUEST_TEMPLATE.md

This PR introduces standardized templates for issues and pull requests to improve contributor experience and streamline project collaboration.
- Added `.github/ISSUE_TEMPLATE/bug_report.md` – Standard bug report format
- Added `.github/ISSUE_TEMPLATE/feature_request.md` – Standard feature request format
- Added `.github/ISSUE_TEMPLATE/custom.md` – Flexible template for other issues
- Added `.github/PULL_REQUEST_TEMPLATE.md` – PR template to ensure consistency
- Makes issue tracking more structured
- Helps contributors provide necessary details upfront
- Improves review process for pull requests
- Enhances overall project maintenance
.github/
├─ ISSUE_TEMPLATE/
│ ├─ bug_report.md
│ ├─ feature_request.md
│ └─ custom.md
└─ PULL_REQUEST_TEMPLATE.md

chore: add issue and PR templates
